import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Feedback App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1>KXLAA</h1>
      </main>
    </>
  );
}
